[package]
name = "get-files"
version = "0.0.1"
authors = ["Jascha Ehrenreich <jascha@jaeh.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
